version: "3.8"
services:
  site1:
    image: nginx:alpine
    container_name: site1
    ports:
      - "8091:80"
    volumes:
      - ./site1:/usr/share/nginx/html:ro
    restart: unless-stopped

  site2:
    image: nginx:alpine
    container_name: site2
    ports:
      - "8092:80"
    volumes:
      - ./site2:/usr/share/nginx/html:ro
    restart: unless-stopped

