version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    group_add:
      - "999"
    restart: unless-stopped
    networks:
      - jenkins-network

volumes:
  jenkins-data:
    external: true

networks:
  jenkins-network:
    driver: bridge
